id: A384A8A32
title: f1AC3
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:31:58.973493
  last_modified_at: 2022-05-27 14:31:58.973498
