id: A384A8A32
title: f7434
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:31:59.148756
  last_modified_at: 2022-05-27 14:31:59.148759
