id: A384A8A32
title: f40B0
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:31:59.020814
  last_modified_at: 2022-05-27 14:31:59.020817
